const deck=document.getElementById('deck');
const omitted=new Set(['卫星图与DXF','初步功能布局生成','分区功能与指标']);
[...document.querySelectorAll('.slide')].forEach(s=>{if(omitted.has(s.dataset.title))s.remove()});
const pageOrder=['项目封面','项目所在地定位','区域三维城市背景','场地高程及坡度示意','规划条件','SU三维交互模型','概念分析','体块生成与总平面','鸟瞰效果一','鸟瞰效果二','夜景鸟瞰二','故事板二','综合经济技术指标','工程造价估算','方案结论','项目封底'];
pageOrder.forEach(title=>{const s=[...deck.querySelectorAll('.slide')].find(x=>x.dataset.title===title);if(s)deck.appendChild(s)});
const chapterLabels={'体块生成与总平面':'第三部分 / 方案展示','综合经济技术指标':'第四部分 / 指标与投资','工程造价估算':'第四部分 / 指标与投资','方案结论':'汇报结论 / 下一步'};
Object.entries(chapterLabels).forEach(([title,label])=>{const s=[...deck.querySelectorAll('.slide')].find(x=>x.dataset.title===title),e=s?.querySelector('.eyebrow');if(e)e.textContent=label});
const slides=[...document.querySelectorAll('.slide')];let index=0;const counter=document.getElementById('counter'),bar=document.getElementById('progressBar');function show(i){index=Math.max(0,Math.min(slides.length-1,i));slides.forEach((s,n)=>s.classList.toggle('active',n===index));counter.textContent=String(index+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');bar.style.width=((index+1)/slides.length*100)+'%';document.title=slides[index].dataset.title+'｜绵阳科技城临港经济发展西区场站配套基础设施建设项目';}document.getElementById('next').onclick=()=>show(index+1);document.getElementById('prev').onclick=()=>show(index-1);document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(index+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(index-1)}});show(Number(new URLSearchParams(location.search).get('page')||1)-1);
const locationTitles=['01｜绵阳市域','02｜项目周边','03｜项目红线'];
const locationHints=['点击图面进入项目周边','点击图面叠加项目红线','卫星图与DXF合图定位基准'];
let locationStep=0;function showLocationStep(step){const box=document.getElementById('locationSequence');if(!box)return;locationStep=Math.max(0,Math.min(2,step));box.className='location-sequence image-frame step-'+locationStep;box.querySelectorAll(':scope>img').forEach((img,i)=>img.classList.toggle('active',i===locationStep));document.querySelectorAll('[data-location-step]').forEach((b,i)=>b.classList.toggle('active',i===locationStep));document.getElementById('locationStepTitle').textContent=locationTitles[locationStep];document.getElementById('locationStepHint').textContent=locationHints[locationStep]}
document.querySelector('.sequence-hit')?.addEventListener('click',()=>showLocationStep((locationStep+1)%3));document.querySelectorAll('[data-location-step]').forEach(b=>b.addEventListener('click',()=>showLocationStep(Number(b.dataset.locationStep))));showLocationStep(Number(new URLSearchParams(location.search).get('loc')||0));
const locationSequence=document.getElementById('locationSequence');
if(locationSequence&&!locationSequence.parentElement.classList.contains('location-analysis-layout')){
  const layout=document.createElement('div');layout.className='location-analysis-layout';
  locationSequence.parentNode.insertBefore(layout,locationSequence);layout.appendChild(locationSequence);
  const condition=document.createElement('aside');condition.className='planning-boundary-panel image-frame';
  condition.innerHTML='<img src="assets/planning-boundary.png" alt="绵自然资规设（2024）181号地块规划条件用地范围图"><div><b>规划条件用地范围</b><span>绵自然资规设（2024）181号｜A/B/C/D地块</span></div>';
  layout.appendChild(condition);
}
const masterplan=document.querySelector('[data-title="体块生成与总平面"] .plan-wrap img');if(masterplan){masterplan.src='assets/masterplan-entrances-v65.png';masterplan.alt='彩色总平面、园区出入口及10/11号配套设施'}
locationSequence?.querySelector('.sequence-site')?.remove();
const locationIntro=document.querySelector('[data-title="项目所在地定位"] .section-head p:not(.eyebrow)');
if(locationIntro){locationIntro.classList.add('planning-land-description');locationIntro.innerHTML='规划用地性质：铁路用地兼容一类物流仓储用地及相关配套的行政办公用地。<br>规划用地面积：245460.29平方米<br>其中，A地块：68902.59平方米　B地块：173035.38平方米<br>C地块：3508.02平方米　D地块：14.30平方米';}
document.querySelector('#modelCanvas .model-toggles')?.remove();
const conclusionCards=document.querySelectorAll('[data-title="方案结论"] .conclusion-grid p');
if(conclusionCards[0])conclusionCards[0].textContent='铁岗大道是唯一城市道路界面，也是园区主要形象展示面，园区主入口均开在此路，但铁岗大道属于快速路，后期开口需与规划与交管部门沟通，可能需要做交评论证；';
if(conclusionCards[1])conclusionCards[1].textContent='北侧用地档案、金库、安保、保税仓储与一期海关监管形成专业组团。南侧用地办公、酒店、汽修配套以及灵活仓储用房更注重多元产业配套';
const zoneText={privacy:'档案室、金库、配套办公和宿舍放在 A 地块最北端，远离城市界面和主要货运流线，保证专业功能的私密性。',bonded:'保税仓库与一期海关监管设施相邻，便于统一监管、装卸组织和一体化运营管理。',city:'B 地块临城市主干道布局配套办公和酒店，形成城市形象界面；汽配、汽检、汽修和汽车美容紧邻办公酒店，突出商业服务属性。',logistics:'沿场地纵深依次组织两栋仓储、冻库、充电站＋换电站＋停车场和露天光伏储能区域，结合 W3/W4/W5/W7 的 12 米、3% 坡道形成连续物流联系。'};document.querySelectorAll('.layout-notes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.layout-notes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('zoneText').textContent=zoneText[b.dataset.zone];window.SU_MOUNTS?.layout?.highlight(b.dataset.zone)});
const defaults=[1800,2000,2200,2000,450,450,1200,1800];const costItems=[['仓储建筑',1800,183766.35],['办公/宿舍',2000,21580.68],['酒店',2200,6549.12],['汽修汽检',2000,37874.78],['道路及场地',450,30000],['绿化及景观',450,12273.01],['坡道构筑物',1200,11200],['充换电/光伏储能',1800,5000]];let costValues=[...defaults];const cc=document.getElementById('costControls'),bars=document.getElementById('costBars'),totalEl=document.getElementById('costTotal');function renderCost(){if(!cc)return;cc.innerHTML='';bars.innerHTML='';let sum=0,vals=[];costItems.forEach((it,i)=>{let row=document.createElement('div');row.className='cost-row';row.innerHTML='<label>'+it[0]+'</label><input type="range" min="0" max="'+Math.round(it[1]*1.6)+'" value="'+costValues[i]+'" step="50"><output>'+costValues[i]+' 元/㎡</output>';let input=row.querySelector('input'),out=row.querySelector('output');input.oninput=()=>{costValues[i]=Number(input.value);out.textContent=costValues[i]+' 元/㎡';renderCost()};cc.appendChild(row);let v=costValues[i]*it[2];sum+=v;vals.push([it[0],v])});totalEl.textContent=(sum/1e8).toFixed(2);vals.sort((a,b)=>b[1]-a[1]).forEach(v=>{let row=document.createElement('div');row.className='bar';row.innerHTML='<span>'+v[0]+'</span><i style="width:'+Math.max(5,v[1]/sum*100)+'%"></i><b>'+ (v[1]/1e8).toFixed(2)+'亿</b>';bars.appendChild(row)})}renderCost();document.getElementById('resetCost')?.addEventListener('click',()=>{costValues=[...defaults];renderCost()});
