(function(){
function create(id,statusId,cityMode){
  const mount=document.getElementById(id);if(!mount)return;
  const scene=new THREE.Scene();scene.background=new THREE.Color(cityMode?0xe8efed:0x071824);
  const camera=new THREE.PerspectiveCamera(42,1,.1,20000);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));mount.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xe4f7f1,0x243c48,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(300,500,260);scene.add(sun);
  let yaw=.38,pitch=.62,dist=cityMode?1500:360,drag=false,moved=false,lx=0,ly=0,mode='normal',tool=null,terrain=null,regionalTerrain=null,terrainBox=null,origin=[0,0,0],colors={normal:null,elevation:null,slope:null},marker=null,sectionLine=null,sectionStart=null;
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
  function resize(){const r=mount.getBoundingClientRect();if(r.width<2)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
  new ResizeObserver(resize).observe(mount);window.addEventListener('resize',resize);
  function cam(){camera.position.set(Math.cos(yaw)*Math.cos(pitch)*dist,Math.sin(pitch)*dist,Math.sin(yaw)*Math.cos(pitch)*dist);camera.lookAt(0,0,0)}
  function linePath(g,path,mat,tx,closed,level){const y=level===undefined?tx.offsetY-.8:level,pts=path.map(q=>new THREE.Vector3(q[0]*tx.scale+tx.offsetX,y,q[1]*tx.scale+tx.offsetZ));if(pts.length<2)return;g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(closed?pts.concat([pts[0]]):pts),mat))}
  function addDxfBase(tx){const d=window.CITY_DXF,g=new THREE.Group(),base=tx.offsetY-1.2;
    if(d){const roadMat=new THREE.LineBasicMaterial({color:0xd7af43,transparent:true,opacity:.74,depthWrite:false}),railMat=new THREE.LineBasicMaterial({color:0x315f98,transparent:true,opacity:.82,depthWrite:false}),buildMat=new THREE.LineBasicMaterial({color:0x647b79,transparent:true,opacity:.48,depthWrite:false});(d.roads||[]).forEach(p=>linePath(g,p,roadMat,tx,false,base));(d.rails||[]).forEach(p=>linePath(g,p,railMat,tx,false,base-.15));(d.buildings||[]).forEach(p=>linePath(g,p,buildMat,tx,true,base-.25))}
    const red=window.DXF_REDLINES;if(red){const redMat=new THREE.MeshBasicMaterial({color:0xff2020,depthWrite:false}),redLevel=base+.02;red.paths.forEach(r=>{const pts=r.path.map(q=>new THREE.Vector3(q[0]*tx.scale+tx.offsetX,redLevel,q[1]*tx.scale+tx.offsetZ));if(pts.length<2)return;const curve=new THREE.CurvePath();pts.forEach((p,i)=>curve.add(new THREE.LineCurve3(p,pts[(i+1)%pts.length])));const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,Math.max(40,pts.length*2),Math.max(.45,tx.scale*1.1),6,true),redMat);g.add(tube)})}
    scene.add(g)
  }
  function addContext(tx){const osm=window.OSM_CITY,g=new THREE.Group();
    if(osm){const roadMat=new THREE.LineBasicMaterial({color:0xc4932f,transparent:true,opacity:.46,depthWrite:false}),railMat=new THREE.LineBasicMaterial({color:0x365e9c,transparent:true,opacity:.58,depthWrite:false});(osm.roads||[]).forEach(p=>linePath(g,p,roadMat,tx,false,tx.offsetY-1.5));(osm.rails||[]).forEach(p=>linePath(g,p,railMat,tx,false,tx.offsetY-1.7));const mat=new THREE.MeshStandardMaterial({color:0xc8d1cb,roughness:.95,transparent:true,opacity:.62});(osm.buildings||[]).forEach(b=>{const pts=b.p||[];if(pts.length<3)return;const shape=new THREE.Shape();pts.forEach((p,i)=>{const x=p[0]*tx.scale+tx.offsetX,z=p[1]*tx.scale+tx.offsetZ;i?shape.lineTo(x,z):shape.moveTo(x,z)});const geom=new THREE.ExtrudeGeometry(shape,{depth:Math.max(1,(b.h||6)*tx.scale),bevelEnabled:false});geom.rotateX(Math.PI/2);const mesh=new THREE.Mesh(geom,mat);mesh.position.y=tx.offsetY;g.add(mesh)})}
    scene.add(g)
  }
  function addRegionalTerrain(tx){const d=window.AWS_TERRAIN;if(!d)return;const pos=[],idx=[],cols=[],zs=d.vertices.map(v=>v[2]),zmin=Math.min(...zs),zmax=Math.max(...zs);d.vertices.forEach(v=>{pos.push(v[0]*tx.scale+tx.offsetX,v[2]*tx.scale+tx.offsetY-1,v[1]*tx.scale+tx.offsetZ);const t=ramp(v[2],zmin,zmax);cols.push(.72+.12*t,.78+.12*t,.72+.08*t)});d.triangles.forEach(t=>idx.push(t[0],t[1],t[2]));const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));geo.setIndex(idx);geo.computeVertexNormals();regionalTerrain=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,side:THREE.DoubleSide,transparent:true,opacity:.82}));regionalTerrain.userData={regional:true,tx};scene.add(regionalTerrain);terrainBox.union(new THREE.Box3().setFromObject(regionalTerrain))}
  function ramp(v,a,b){return Math.max(0,Math.min(1,(v-a)/(b-a||1)))}
  function hsl(h,s,l){const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return[r+m,g+m,b+m]}
  function parseGlb(ab){const dv=new DataView(ab);if(dv.getUint32(0,true)!==0x46546c67)throw Error('invalid GLB');let o=12,j=null,bin=null;while(o<dv.byteLength){const n=dv.getUint32(o,true),t=dv.getUint32(o+4,true),b=ab.slice(o+8,o+8+n);if(t===0x4e4f534a)j=JSON.parse(new TextDecoder().decode(b).replace(/\0+$/,''));if(t===0x004e4942)bin=b;o+=8+n}function read(ai){const a=j.accessors[ai],v=j.bufferViews[a.bufferView],n=a.type==='VEC3'?3:1,C=a.componentType===5126?Float32Array:Uint32Array,x=new C(bin,(v.byteOffset||0)+(a.byteOffset||0),a.count*n),out=[];for(let i=0;i<x.length;i+=n)out.push(n===3?[x[i],x[i+1],x[i+2]]:x[i]);return out}const p=j.meshes[0].primitives[0];return{mesh:{webAxes:true,vertices:read(p.attributes.POSITION),triangles:read(p.indices).reduce((a,v,i)=>(i%3?a[a.length-1].push(v):a.push([v]),a),[])}}}
  function addTerrain(data){
    const vs=data.mesh.vertices.map(v=>Array.isArray(v)?v:v.split(' ').map(Number)),ts=data.mesh.triangles,pos=[],idx=[];origin=(window.TERRAIN_DATA&&window.TERRAIN_DATA.mesh&&window.TERRAIN_DATA.mesh.origin)||data.mesh.origin||[0,0,0];
    if(data.mesh.webAxes){vs.forEach(v=>pos.push(v[0],v[1],v[2]));ts.forEach(t=>idx.push(t[0],t[1],t[2]))}else{vs.forEach(v=>pos.push(v[0],v[2],v[1]));ts.forEach(t=>idx.push(t[0],t[2],t[1]))}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();
    const zs=vs.map(v=>data.mesh.webAxes?v[1]:v[2]),zmin=Math.min(...zs),zmax=Math.max(...zs),norm=geo.getAttribute('normal'),cn=[],ce=[],cs=[];for(let i=0;i<vs.length;i++){const z=ramp(zs[i],zmin,zmax),sl=ramp(1-Math.abs(norm.getY(i)),0,.72);cn.push(.33+.12*z,.53+.2*z,.42+.14*z);ce.push(...hsl(220-220*z,.72,.48));cs.push(...hsl(52-52*sl,.78,.48))}
    colors={normal:new Float32Array(cn),elevation:new Float32Array(ce),slope:new Float32Array(cs)};geo.setAttribute('color',new THREE.Float32BufferAttribute(colors.normal,3));terrain=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.94,side:THREE.DoubleSide}));
    terrain.material.transparent=true;terrain.material.opacity=cityMode?.5:.38;terrain.material.depthWrite=false;terrain.renderOrder=2;
    const box=new THREE.Box3().setFromObject(terrain),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),scale=(cityMode?390:300)/Math.max(size.x,size.z);terrain.scale.setScalar(scale);terrain.position.set(-center.x*scale,-20-center.y*scale,-center.z*scale);scene.add(terrain);terrain.updateMatrixWorld(true);terrainBox=new THREE.Box3().setFromObject(terrain);
    const tx={scale,offsetX:-center.x*scale,offsetY:-20-center.y*scale,offsetZ:-center.z*scale};addDxfBase(tx);if(cityMode){addRegionalTerrain(tx);addContext(tx)}
    const s=document.getElementById(statusId);if(s)s.textContent=cityMode?'3公里城市背景＋项目地形｜道路线位于地形下方':'原始场地＋DXF底图｜规划红线已加粗';apply()
  }
  function apply(){if(!terrain)return;const a=terrain.geometry.getAttribute('color'),src=colors[mode]||colors.normal;a.array.set(src);a.needsUpdate=true;if(regionalTerrain){regionalTerrain.material.opacity=.5;regionalTerrain.material.depthWrite=false;regionalTerrain.renderOrder=1}}
  function setTool(next){tool=tool===next?null:next;sectionStart=null;mount.classList.toggle('is-query',tool==='query');mount.classList.toggle('is-section',tool==='section');mount.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('tool-active',b.dataset.tool===tool));mount.querySelector('.terrain-tool-hint')?.remove();if(tool){const hint=document.createElement('div');hint.className='terrain-tool-hint';hint.textContent=tool==='query'?'点击地形读取坐标、标高和坡度':'依次点击地形剖面的起点与终点';mount.appendChild(hint)}}
  function terrainHit(e){if(!terrain)return null;const r=renderer.domElement.getBoundingClientRect();pointer.set(1-(e.clientX-r.left)/r.width*2,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(regionalTerrain?[terrain,regionalTerrain]:[terrain],false)[0]||null}
  function localData(hit){const normal=hit.face?hit.face.normal:new THREE.Vector3(0,1,0),slope=Math.acos(Math.min(1,Math.abs(normal.y)))*180/Math.PI;if(hit.object.userData.regional){const tx=hit.object.userData.tx,x=(hit.point.x-tx.offsetX)/tx.scale,north=(hit.point.z-tx.offsetZ)/tx.scale,z=(hit.point.y+1-tx.offsetY)/tx.scale;return{e:+origin[0]+x,n:+origin[1]+north,z:+origin[2]+z,slope}}const local=terrain.worldToLocal(hit.point.clone());return{local,e:+origin[0]+local.x,n:+origin[1]+local.z,z:+origin[2]+local.y,slope}}
  function showPoint(hit){const d=localData(hit);if(marker)scene.remove(marker);marker=new THREE.Mesh(new THREE.SphereGeometry(3.2,16,12),new THREE.MeshBasicMaterial({color:0xef4040}));marker.position.copy(hit.point).add(new THREE.Vector3(0,3,0));scene.add(marker);let box=mount.querySelector('.terrain-readout');if(!box){box=document.createElement('div');box.className='terrain-readout';mount.appendChild(box)}box.innerHTML='<strong>地形点查询</strong>东坐标：'+d.e.toFixed(2)+' m<br>北坐标：'+d.n.toFixed(2)+' m<br>模型标高：'+d.z.toFixed(2)+' m<br>坡度：'+d.slope.toFixed(1)+'°'}
  function sampleSection(a,b){const samples=[],count=100,scale=terrain.scale.x,length=Math.hypot(b.x-a.x,b.z-a.z)/scale,targets=regionalTerrain?[terrain,regionalTerrain]:[terrain];for(let i=0;i<=count;i++){const t=i/count,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;raycaster.set(new THREE.Vector3(x,terrainBox.max.y+80,z),new THREE.Vector3(0,-1,0));const hit=raycaster.intersectObjects(targets,false)[0];if(hit)samples.push({d:length*t,z:localData(hit).z})}return{samples,length}}
  function drawProfile(result){mount.querySelector('.terrain-readout')?.remove();let panel=mount.querySelector('.terrain-profile');if(!panel){panel=document.createElement('div');panel.className='terrain-profile';mount.appendChild(panel)}const zs=result.samples.map(p=>p.z),zmin=Math.min(...zs),zmax=Math.max(...zs),w=1000,h=100,pad=8,range=zmax-zmin||1,pts=result.samples.map(p=>[pad+(p.d/result.length)*(w-pad*2),h-pad-((p.z-zmin)/range)*(h-pad*2)]),line=pts.map(p=>p.join(',')).join(' '),area=pad+','+(h-pad)+' '+line+' '+(w-pad)+','+(h-pad);panel.innerHTML='<header><b>地形剖面｜长度 '+result.length.toFixed(1)+' m</b><span>最低 '+zmin.toFixed(2)+' m　最高 '+zmax.toFixed(2)+' m</span></header><svg viewBox="0 0 1000 100" preserveAspectRatio="none"><line class="profile-grid" x1="8" y1="92" x2="992" y2="92"></line><line class="profile-grid" x1="8" y1="8" x2="8" y2="92"></line><polygon class="profile-fill" points="'+area+'"></polygon><polyline class="profile-line" points="'+line+'"></polyline></svg>'}
  function handleTool(e){const hit=terrainHit(e);if(!hit)return;if(tool==='query'){showPoint(hit);return}if(tool==='section'){if(!sectionStart){sectionStart=hit.point.clone();showPoint(hit);const hint=mount.querySelector('.terrain-tool-hint');if(hint)hint.textContent='已选起点，请点击剖面终点';return}const end=hit.point.clone();if(sectionLine)scene.remove(sectionLine);sectionLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([sectionStart.clone().add(new THREE.Vector3(0,2,0)),end.clone().add(new THREE.Vector3(0,2,0))]),new THREE.LineBasicMaterial({color:0xef4040}));scene.add(sectionLine);const result=sampleSection(sectionStart,end);if(result.samples.length>1)drawProfile(result);sectionStart=null;const hint=mount.querySelector('.terrain-tool-hint');if(hint)hint.textContent='剖面已生成，可继续选择新的起点与终点'}}
  function reset(){yaw=.38;pitch=.62;dist=cityMode?1500:360;mode='normal';setTool(null);mount.querySelectorAll('[data-terrain]').forEach(b=>b.classList.toggle('active',b.dataset.terrain==='normal'));mount.querySelector('.terrain-readout')?.remove();mount.querySelector('.terrain-profile')?.remove();if(marker){scene.remove(marker);marker=null}if(sectionLine){scene.remove(sectionLine);sectionLine=null}cam();apply()}
  cam();const glbPromise=window.ORIGINAL_SITE_GLB?Promise.resolve(Uint8Array.from(atob(window.ORIGINAL_SITE_GLB),c=>c.charCodeAt(0)).buffer):Promise.reject(Error('离线场地模型数据缺失'));glbPromise.then(parseGlb).catch(()=>window.TERRAIN_DATA).then(addTerrain).catch(()=>{const s=document.getElementById(statusId);if(s)s.textContent='原始场地模型网格加载失败'});
  mount.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag=true;moved=false;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});
  mount.addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-lx,e.clientY-ly)>3)moved=true;if(!tool){yaw-=(e.clientX-lx)*.008;pitch=Math.max(-1.15,Math.min(1.15,pitch+(e.clientY-ly)*.006));cam()}lx=e.clientX;ly=e.clientY});
  mount.addEventListener('pointerup',e=>{if(!drag)return;drag=false;if(tool&&!moved)handleTool(e)});
  mount.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(170,Math.min(2400,dist*(e.deltaY>0?1.08:.92)));cam()},{passive:false});
  mount.querySelectorAll('[data-terrain]').forEach(b=>b.addEventListener('click',()=>{mount.querySelectorAll('[data-terrain]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.terrain;apply()}));
  mount.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tool==='reset')reset();else setTool(b.dataset.tool)}));
  function animate(){requestAnimationFrame(animate);renderer.render(scene,camera)}animate()
}
create('terrainCanvas','terrainStatus',false);create('cityCanvas','cityStatus',true);
})();
